name: Airflow Workflow

on:
  push:
    branches:
      - main

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install apache-airflow
        airflow initdb

    - name: Create DAGs directory
      run: mkdir -p $GITHUB_WORKSPACE/dags/

    - name: Copy DAG file
      run: cp my_dag.py $GITHUB_WORKSPACE/dags/

    - name: Start Airflow Web Server
      run: airflow webserver --port 8080 --host 0.0.0.0

    - name: Display Airflow UI URL
      run: echo "Airflow UI URL: http://localhost:8080"
